<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<a target='_blank' href="01-Dec-2016__07_39_05PM.png">Capture Screenshot</a>]]>
    </line>
  </reporter-output>
  <suite name="TestNG Learning" duration-ms="8175" started-at="2016-12-01T14:08:59Z" finished-at="2016-12-01T14:09:07Z">
    <groups>
    </groups>
    <test name="Selendroid App Test" duration-ms="8175" started-at="2016-12-01T14:08:59Z" finished-at="2016-12-01T14:09:07Z">
      <class name="testcases.care.CareLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.care.CareLoginTest@f2ff811]" name="setUp" is-config="true" duration-ms="11095" started-at="2016-12-01T19:38:48Z" finished-at="2016-12-01T19:38:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="init()[pri:0, instance:testcases.care.CareLoginTest@f2ff811]" name="init" is-config="true" duration-ms="216" started-at="2016-12-01T19:38:59Z" finished-at="2016-12-01T19:38:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="validateButtons()[pri:0, instance:testcases.care.CareLoginTest@f2ff811]" name="validateButtons" duration-ms="2502" started-at="2016-12-01T19:38:59Z" finished-at="2016-12-01T19:39:01Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<4> but was:<3>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<4> but was:<3>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at testcases.care.CareLoginTest.validateButtons(CareLoginTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[<a target='_blank' href="01-Dec-2016__07_39_05PM.png">Capture Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateButtons -->
        <test-method status="PASS" signature="SignUpWithEmail()[pri:0, instance:testcases.care.CareLoginTest@f2ff811]" name="SignUpWithEmail" duration-ms="1377" started-at="2016-12-01T19:39:05Z" finished-at="2016-12-01T19:39:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUpWithEmail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.care.CareLoginTest@f2ff811]" name="tearDown" is-config="true" duration-ms="1133" started-at="2016-12-01T19:39:07Z" finished-at="2016-12-01T19:39:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.care.CareLoginTest -->
    </test> <!-- Selendroid App Test -->
  </suite> <!-- TestNG Learning -->
</testng-results>
