<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Selendroid App Test"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="3.879">
  <properties />
            <testcase name="validateButtons" time="2.502" classname="testcases.care.CareLoginTest">
                <failure type="junit.framework.AssertionFailedError"
                  message="expected:&lt;4&gt; but was:&lt;3&gt;"
              >
<![CDATA[junit.framework.AssertionFailedError: expected:<4> but was:<3>
  junit.framework.Assert.fail(Assert.java:50)
  junit.framework.Assert.failNotEquals(Assert.java:287)
  junit.framework.Assert.assertEquals(Assert.java:67)
  junit.framework.Assert.assertEquals(Assert.java:199)
  junit.framework.Assert.assertEquals(Assert.java:205)
  testcases.care.CareLoginTest.validateButtons(CareLoginTest.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:773)
  org.testng.TestRunner.run(TestRunner.java:623)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
  org.testng.TestNG.run(TestNG.java:1018)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="SignUpWithEmail" time="1.377" classname="testcases.care.CareLoginTest" />
      
</testsuite>
